### ISSUE TITLE
FOR UPDATE not support

### ISSUE THREAD

**Issue by likun1234** [klahnakoski/mo-sql-parsing#129]
for SQL like `select * from bmsql_config for update;`, it report the following errors:
Traceback (most recent call last):
  File "parser/sql_parsing.py", line 592, in <module>
    print(parse(sql32))
  File "site-packages\mo_sql_parsing\__init__.py", line 37, in parse
    result = _parse(common_parser, sql, null, calls)
  File "\site-packages\mo_sql_parsing\__init__.py", line 78, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "site-packages\mo_parsing\core.py", line 80, in output
    return func(*args, **kwargs)
  File "site-packages\mo_parsing\core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
  File "site-packages\mo_parsing\core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {with ordinality} | {tablesample} | {join} | {StringEnd} | {with} | {where} | {group by} | {having} | {qualify} | {order by} | {offset} | {fetch} | {limit} | {as}, found "update" (at char 31), (line:1, col:32)

**Comment by klahnakoski** [comment]
https://www.cockroachlabs.com/blog/select-for-update/

**Comment by klahnakoski** [comment]
https://www.postgresql.org/docs/current/sql-select.html

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/ea674eb638acb61592d822cebfeb837a69fafd4d

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.211.22288/
