### ISSUE TITLE
ParseException on CREATE TABLE with unqualified KEY

### ISSUE THREAD

**Issue by krivard** [klahnakoski/mo-sql-parsing#139]
## What happens

mo-sql-parsing raises a ParseException for plain vanilla (i.e. not UNIQUE, PRIMARY, or FOREIGN) KEYs

## Steps to reproduce

```
sql = """
CREATE TABLE `a_table` (
  `a_column` INT,
  KEY `a_key` (`a_column`),
)
"""
mo_sql_parsing.parse_mysql(sql)
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 53, in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
  File "/usr/local/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 78, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 80, in output
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting ), found "(`a_column" (at char 58), (line:4, col:15)
```

## Context

I'm working on a project that uses several keys for fast lookups on a subset of key columns. 

Switching to INDEX doesn't work. 

Prepending the lines with UNIQUE will parse, but we don't actually want our database doing uniqueness checks for these keys.

As an experiment I dropped the key part expression, and the parser's apparently trying to interpret `KEY` as a column name. Given:

```
CREATE TABLE `a_table` (
  `a_column` INT,
  KEY `a_key`
)
```

the result is:
```
{
  "create table": {
    "name": "a_table",
    "columns": [
      {
        "name": "a_column",
        "type": {
          "int": {}
        }
      },
      {
        "name": "KEY",
        "type": "a_key"
      }
    ],
  }
}
```

**Comment by klahnakoski** [comment]
I will look into this tomorrow.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/8b7e0215d5e5f42e36ce66d1c5ba2894cc958c1f

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.236.22315/
