### ISSUE TITLE
TRUNCATE [TABLE] table_name' raises exception

### ISSUE THREAD

**Issue by SerGeRybakov** [klahnakoski/mo-sql-parsing#179]
Hi! Is `TRUNCATE` token is broken or not supported at all?
I tried both 
```py
mo_sql_parsing.parse("TRUNCATE TABLE table_name;")
``` 
and 
```py
mo_sql_parsing.parse("TRUNCATE table_name;")
```
   
The result is the same: 
```py 
mo_parsing.exceptions.ParseException: Expecting {explain} | {statement}, found "TRUNCATE t" (at char 0), (line:1, col:1)
```

Full trace:
```py
Traceback (most recent call last):
  File "/home/serge/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.8770.66/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/serge/owm/deker/deker_embedded/venv/lib/python3.10/site-packages/mo_sql_parsing/__init__.py", line 39, in parse
    result = _parse(common_parser, sql, null, calls)
  File "/home/serge/owm/deker/deker_embedded/venv/lib/python3.10/site-packages/mo_sql_parsing/__init__.py", line 80, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "/home/serge/owm/deker/deker_embedded/venv/lib/python3.10/site-packages/mo_parsing/core.py", line 80, in output
    return func(*args, **kwargs)
  File "/home/serge/owm/deker/deker_embedded/venv/lib/python3.10/site-packages/mo_parsing/core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
  File "/home/serge/owm/deker/deker_embedded/venv/lib/python3.10/site-packages/mo_parsing/core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {explain} | {statement}, found "TRUNCATE t" (at char 0), (line:1, col:1)
```

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/6add0c5a12a19458ed071813bce4d51c0ce04205

**Comment by klahnakoski** [comment]
Thank you very much for reporting this oversight

https://pypi.org/project/mo-sql-parsing/9.401.23144/

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-sql-parsing/commit/72ed6c7c2754d0a94d1212883629b3f7278a9015

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.402.23144/
