### ISSUE TITLE
Fail to parse "INSERT INTO target(column1, column2) SELECT..."

### ISSUE THREAD

**Issue by joelee** [klahnakoski/mo-sql-parsing#183]
Failed to parse query: `INSERT INTO bazz (xname, fname) SELECT f.Name, m.FieldName FROM foo as f LEFT JOIN moo as m ON f.id=m.id WHERE f,Type = 'Test' ORDER BY f.SortField DESC LIMIT 10 OFFSET 100`

```
>>> parse("INSERT INTO bazz (xname, fname) SELECT f.Name, m.FieldName FROM foo as f LEFT JOIN moo as m ON f.id=m.id WHERE f,Type = 'Test' ORDER BY f.SortField DESC LIMIT 10 OFFSET 100")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joseph.lee/.virtualenvs/sql-lineage-parser-XKmSe0Wi-py3.11/lib/python3.11/site-packages/mo_sql_parsing/__init__.py", line 39, in parse
    result = _parse(common_parser, sql, null, calls)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph.lee/.virtualenvs/sql-lineage-parser-XKmSe0Wi-py3.11/lib/python3.11/site-packages/mo_sql_parsing/__init__.py", line 80, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph.lee/.virtualenvs/sql-lineage-parser-XKmSe0Wi-py3.11/lib/python3.11/site-packages/mo_parsing/core.py", line 80, in output
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph.lee/.virtualenvs/sql-lineage-parser-XKmSe0Wi-py3.11/lib/python3.11/site-packages/mo_parsing/core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph.lee/.virtualenvs/sql-lineage-parser-XKmSe0Wi-py3.11/lib/python3.11/site-packages/mo_parsing/core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting {StringEnd} | {group} | {having} | {window} | {qualify} | {order} | {offset} | {fetch} | {limit} | {for} | {expression}, found ",Type = 'T" (at char 112), (line:1, col:113)
>>> parse(INSERT INTO bazz (xname, fname) SELECT f.Name, m.FieldName FROM foo as f LEFT JOIN moo as m ON f.id=m.id WHERE f.Type = 'Test' ORDER BY f.SortField DESC LIMIT 10 OFFSET 100)
  File "<stdin>", line 1
    parse(INSERT INTO bazz (xname, fname) SELECT f.Name, m.FieldName FROM foo as f LEFT JOIN moo as m ON f.id=m.id WHERE f.Type = 'Test' ORDER BY f.SortField DESC LIMIT 10 OFFSET 100)
          ^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by klahnakoski** [comment]
@joelee 


I see your first parse failed because of a comma.  

![image](https://github.com/klahnakoski/mo-sql-parsing/assets/2334429/9390e334-e7b7-4a10-b1ff-7bf9a0456ec6)

The second failure happened because the SQL was not in a string, and the Python interpreter could not parse it.
