### ISSUE TITLE
"using btree" in create query raises a bug

### ISSUE THREAD

**Issue by onlyacat** [klahnakoski/mo-sql-parsing#187]
reproduce(same as ``mo_sql_parsing.parse_mysql``):
```
import mo_sql_parsing
mo_sql_parsing.parse("create table tt (n varchar(10), nn varchar(6), key `inx_nn` (`nn`) using btree );")
```
then an exception found:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/mo_sql_parsing/__init__.py", line 39, in parse
    result = _parse(common_parser, sql, null, calls)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mo_sql_parsing/__init__.py", line 80, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mo_parsing/core.py", line 80, in output
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mo_parsing/core.py", line 149, in parse
    return self._parseString(string, parse_all=parse_all)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mo_parsing/core.py", line 171, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting identifier, found "using btre" (at char 67), (line:1, col:68)
```

And this sql can be executed successfully by MySQL.

library version:
```
> pip3 list | grep mo
mo-dots            9.417.23168
mo-future          7.416.23168
mo-imports         7.416.23168
mo-parsing         8.421.23188
mo-sql-parsing     9.422.23190
```

**Comment by klahnakoski** [comment]
Thank you for this submission!  https://github.com/klahnakoski/mo-sql-parsing/commit/50b0118fcb5d925140d0e59bcc556c72bcb619e7

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/9.423.23199/
