### ISSUE TITLE
cannot find suitable dependency set for mo-sql-parser... gaggle of problems with dependencies on mo_imports, mo_logs, etc.

### ISSUE THREAD

**Issue by richlysakowski** [klahnakoski/mo-sql-parsing#188]
I am trying (for several hours now) to get this package to run: 

See this github repo for more details:

[ Firefox Places DB Analytics Application ](https://github.com/AndrewRPorter/my-analytics/tree/master)

I am going in circles trying to get this to work.  

I installed using pip install moz-sql-parser, then I got the following errors.  

Then I installed using pip install mo-sql-parser, the supposed replacement for moz-sql-parser, but then I get the error far below...

################################################################
When I install using "pip install moz-sql-parser" I get the following errors from my program.  

Irreconcilable error due to missing export() calls?  

Traceback (most recent call last):
  File "C:\Users\PowerUser\Desktop\!0 - NTAI-Training-Sessions\2023.07.29-Firefox-Usage-DB-Analytics-App\main_v3.py", line 19, in <module>
    from my_analytics.stats import plot
  File "C:\Users\PowerUser\Desktop\!0 - NTAI-Training-Sessions\2023.07.29-Firefox-Usage-DB-Analytics-App\my_analytics\stats\plot.py", line 8, in <module>
    from my_analytics.database import db_interface
  File "C:\Users\PowerUser\Desktop\!0 - NTAI-Training-Sessions\2023.07.29-Firefox-Usage-DB-Analytics-App\my_analytics\database\db_interface.py", line 3, in <module>
    import moz_sql_parser
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\moz_sql_parser\__init__.py", line 15, in <module>
    from moz_sql_parser.sql_parser import SQLParser, scrub_literal, scrub
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\moz_sql_parser\sql_parser.py", line 12, in <module>
    from mo_parsing.engine import Engine
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\mo_parsing\__init__.py", line 60, in <module>
    from mo_parsing.infix import LEFT_ASSOC, RIGHT_ASSOC, infixNotation
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\mo_parsing\infix.py", line 4, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\ProgramData\Anaconda3\envs\streamlit\lib\collections\__init__.py)
missing expected call export("mo_parsing.core", regex_parameters)
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\mo_imports\__init__.py", line 204, in worker
    _error("Missing export() calls")
  File "C:\ProgramData\Anaconda3\envs\streamlit\lib\site-packages\mo_imports\__init__.py", line 211, in _error
    raise Exception(description)
Exception: Missing export() calls

################################################################

When I install using "pip install mo-sql-parser" (the supposed replacement for moz-sql-parser) I get the following errors from pip.

pip install mo-sql-parsing
Collecting mo-sql-parsing
  Obtaining dependency information for mo-sql-parsing from https://files.pythonhosted.org/packages/f7/27/73d0f48c641f65aa91648431757fcfc0deafb453016277852b5ca879b64e/mo_sql_parsing-9.427.23208-py2.py3-none-any.whl.metadata
  Downloading mo_sql_parsing-9.427.23208-py2.py3-none-any.whl.metadata (9.3 kB)
Collecting mo-dots==9.417.23168 (from mo-sql-parsing)
  Obtaining dependency information for mo-dots==9.417.23168 from https://files.pythonhosted.org/packages/db/7b/7cc1c640282a600c2176513db32b3ec10db3865c6b31d0b3c95f1bef0d0f/mo_dots-9.417.23168-py2.py3-none-any.whl.metadata
  Using cached mo_dots-9.417.23168-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting mo-future==7.416.23168 (from mo-sql-parsing)
  Obtaining dependency information for mo-future==7.416.23168 from https://files.pythonhosted.org/packages/2e/75/eb67678353f47bc616eddf19122a1de2b421a5d86d6bc8fa2ff04c999735/mo_future-7.416.23168-py2.py3-none-any.whl.metadata
  Using cached mo_future-7.416.23168-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting mo-imports==7.416.23168 (from mo-sql-parsing)
  Obtaining dependency information for mo-imports==7.416.23168 from https://files.pythonhosted.org/packages/59/0f/1e3fd2ba6bc041988569212eec5f9483fb88a7d4aaf66f5c36fcf7fc1468/mo_imports-7.416.23168-py2.py3-none-any.whl.metadata
  Using cached mo_imports-7.416.23168-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting mo-parsing==8.423.23199 (from mo-sql-parsing)
  Obtaining dependency information for mo-parsing==8.423.23199 from https://files.pythonhosted.org/packages/ea/9b/eb4e86fc7653ebcc1797730dc1df822217ea9c7bbcce4ad54efb44dc378f/mo_parsing-8.423.23199-py2.py3-none-any.whl.metadata
  Downloading mo_parsing-8.423.23199-py2.py3-none-any.whl.metadata (7.7 kB)
Downloading mo_sql_parsing-9.427.23208-py2.py3-none-any.whl (38 kB)
Using cached mo_dots-9.417.23168-py2.py3-none-any.whl (25 kB)
Using cached mo_future-7.416.23168-py2.py3-none-any.whl (10 kB)
Using cached mo_imports-7.416.23168-py2.py3-none-any.whl (11 kB)
Downloading mo_parsing-8.423.23199-py2.py3-none-any.whl (62 kB)
   ---------------------------------------- 62.5/62.5 kB 1.1 MB/s eta 0:00:00
Installing collected packages: mo-future, mo-imports, mo-dots, mo-parsing, mo-sql-parsing
  Attempting uninstall: mo-future
    Found existing installation: mo-future 3.147.20327
    Uninstalling mo-future-3.147.20327:
      Successfully uninstalled mo-future-3.147.20327
  Attempting uninstall: mo-imports
    Found existing installation: mo-imports 3.149.20327
    Uninstalling mo-imports-3.149.20327:
      Successfully uninstalled mo-imports-3.149.20327
  Attempting uninstall: mo-dots
    Found existing installation: mo-dots 4.22.21108
    Uninstalling mo-dots-4.22.21108:
      Successfully uninstalled mo-dots-4.22.21108
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mo-kwargs 4.22.21108 requires mo-dots==4.22.21108, but you have mo-dots 9.417.23168 which is incompatible.
mo-kwargs 4.22.21108 requires mo-future==3.147.20327, but you have mo-future 7.416.23168 which is incompatible.
mo-logs 4.23.21108 requires mo-dots==4.22.21108, but you have mo-dots 9.417.23168 which is incompatible.
mo-logs 4.23.21108 requires mo-future==3.147.20327, but you have mo-future 7.416.23168 which is incompatible.
mo-logs 4.23.21108 requires mo-imports==3.149.20327, but you have mo-imports 7.416.23168 which is incompatible.
Successfully installed mo-dots-9.417.23168 mo-future-7.416.23168 mo-imports-7.416.23168 mo-parsing-8.423.23199 mo-sql-parsing-9.427.23208

#######################################################

Pip is the source of this:

"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts."

I hate pip, because once you hit a dead end, you are dead in the water unless you hack other people's packages.  At least with conda, it resolves these sticky dependencies.  

Can someone suggest some fix(es) for this problem?  I really would like to get this browser history analytics app running to demonstrate some things to my students.  

I will try building a new conda repo just for this one application, and use pip install inside that new conda environment, but this looks like a mo-sql-parser incompatibilties problem with several much mo-**** packages versions.

**Comment by klahnakoski** [comment]
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

Here are some things to try:

* Ignore this pip ERROR because  `mo-sql-parsing` does not use `mo-kwargs` or `mo-logs`.
* `pip install --upgrade` both `mo-kwargs` and `mo-logs` individually; they will still version-conflict with mo-sql-parsing, but the major version will match and there will be no bugs
* I will test-and-release all these packages as a bundle to confirm they run together

The `mo-*` packages do not change much, and work together despite the version conflicts.  This problem you experience is caused by the specific version numbers I put in the setup.py; the specific versions I test with.  When I release one tree of dependencies, it will leave other (overlapping) trees behind.  

I have considered testing more dependency combinations so this problem is less likely to happen; but that may lead to a combination explosion of testing.  I have also considered releasing all modules, even ones only getting a version bump, but that leaves even more not-of-value upgrades it am doing now.

I will get back to you with `mo-sql-parsing`, `mo-kwargs` and `mo-logs` that agree on dependencies

**Comment by klahnakoski** [comment]
... but I spoke too soon.  As far as I can tell, the later versions of the `mo-*` modules do align with `mo-sql-parsing`:  `pip install --upgrade <the module>` will bring the others up to date; and they will agree on dependency trees.

Please get back to me about your progress.

**Comment by richlysakowski** [comment]
Thank you for responding.  I am thinking of creating a new conda virtual
environment "moz_analytics" to start fresh, with only Python (maybe 3.8 or
so, not the latest).  Install conda and pip in the moz_analytics conda
virtual environment for safety purposes, so that pip does not corrupt my
base environment.

It appears as though conda packages have not been created for several of
these mo_*** packages, thus requiring pip to be used.  Then in this conda
environment, I can use PIP to install (and force, i.e. "pin") the specific
versions required by the PIP dependency resolver.  This is a hack to
accommodate pip limitations.  The mo_** packages in that environment cannot
be upgraded,  must be frozen with those dependencies.  I don't normally use
PIP for package, because the conda environment and package manager does a
two-phase commit with environment integrity checking before it does the
final commit of new package installations.

From my memory, it seems that the error with mo-sql-parsing came from the
way that mo-sql-parsing is using the export() function in the Python Std
Lib Collections.  I will double check the errors.

If the other version numbering errors from mo_*** are inconsequential, then
maybe all the package version numbers should be bumped in tandem.  They
seem to be a set of interrelated packages whose version numbers are far out
of sync.  They now range from v9.xx.xxx downward.

My main goal is that I want to get this simple browser analytics
application working.  mo_sql_parser provides the core functionality to work
with SQLite data in Firefox/Mozilla browsers.

I will report back with what I find with pip in a new conda environment.
It may take a little while because I have some other things to do this
weekend.

Best Regards,

Rich Lysakowski

**Comment by klahnakoski** [comment]
> From my memory, it seems that the error with mo-sql-parsing came from the
way that mo-sql-parsing is using the export() function in the Python Std
Lib Collections.  I will double check the errors.

The export error

```
ImportError: cannot import name 'Iterable' from 'collections' (C:\ProgramData\Anaconda3\envs\streamlit\lib\collections_init_.py)
missing expected call export("mo_parsing.core", regex_parameters)
```

 is only a symptom of the failed import

    from collections import Iterable

The `mo-imports` tracks any missing `export()` calls; that can happen when module loading fails.  That is happening here.

**Comment by klahnakoski** [comment]
I cloned the Firefox Places DB Analytics Application  and installed the requirements.txt.  The current firefox schema has changed, so the "model" is stale;  but the code works by not using a model, and leaving the data as a `dict`.

This code does not use the mo-sql-parsing.  Maybe you are working on something else?

![image](https://github.com/klahnakoski/mo-sql-parsing/assets/2334429/d97b7cd5-5326-4b9d-91db-22ade45d7605)

**Comment by richlysakowski** [comment]
I carefully checked my package imports and I saw that I still had moz_sql_parser in one place.    There was a little confusion on my part between the naming of moz_sql_parser and mo_sql_parsing, and more confusion between "mo" and "moz" and "_" and "-" in package names.  (I wish people would stop using minus signs (hyphens) in Python package names, i.e., non-Pythonic object names).  

I uninstalled every mo_** package and reinstalled them all.    The package version stayed the same as below, with the exception of mo_sql_parsing. 

After cleaning up some bad package imports, the application is now working creating and populating the database with Mozilla Places.db data and giving me plots, (plots till need work, but at least they appear).

Here is what I have now:   
```
conda list mo-
# packages in environment at C:\ProgramData\Anaconda3\envs\streamlit:
#
# Name                    Version                   Build  Channel
mo-dots                   9.417.23168              pypi_0    pypi
mo-future                 7.416.23168              pypi_0    pypi
mo-imports                7.416.23168              pypi_0    pypi
mo-kwargs                 4.22.21108               pypi_0    pypi
mo-logs                   4.23.21108               pypi_0    pypi
mo-parsing                8.423.23199              pypi_0    pypi
mo-sql-parsing            9.427.23208              pypi_0    pypi

```
Once I fixed all my imports I got a different error, which I was able to trace to bad package imports in the packages for application "MyAnalytics" (aka "Firefox Places DB Analytics Application").  

I made changes to updated the package "models.py" and that got rid of a sequence of errors like Error: MOZ_PLACE.__init__() got an unexpected keyword argument 'site_name'.   I just added the missing fields one-by-one as the error messages came up.   

I also added a class modifier to deal with these additional fields.  


I changed the imports around in "MyAnalytics" packages so that the objects in models, db_interface, and plots were all import into the session namespace and being referenced correctly.  Some refactoring is in order because I have too many package imports going on.   I think the package structure could be improved slightly.  

These changes resolve the rest of the issues related to the mo_** packages.    The mo_sql_parser errors are resolved now.  

Thank you for your assistance.  With your insight I was able to debug 

#######################################################################
Changes to models.py package to add the following missing fields:     

MOZ_PLACE:
    site_name
    recalc_frecency
    alt_frecency
    recalc_alt_frecency

MOZ_HISTORYVISIT: 
    source
    triggeringPlaceId

#######################################################################

```
from dataclasses import dataclass

## RSL added site_name to the following dataclass because it was missing from the original.
## and the following error was thrown:
## Error: MOZ_PLACE.__init__() got an unexpected keyword argument 'site_name'
## Similar errors occured for other fields that were not included in the dataclass.  
## These were added below at the end as named-value arguments with a value of None.
## This updated the data model. The  unexpected keyword argument errors were resolved.  

@dataclass
class MOZ_PLACE:
    id: int
    url: str
    title: str
    rev_host: str
    visit_count: int
    hidden: int
    typed: int
    frecency: str
    last_visit_date: float
    guid: str
    foreign_count: int
    url_hash: int
    description: str
    preview_image_url: str
    origin_id: int
    site_name: str = None
    recalc_frecency: bool = None
    alt_frecency: bool = None
    recalc_alt_frecency: bool = None


    def __str__(self):
        return str(self.url)


@dataclass
class MOZ_HISTORYVISIT:
    id: int
    from_visit: int
    place_id: int
    visit_date: int
    visit_type: int
    session: int
    source: bool = None
    triggeringPlaceId: bool = None
    
    def __str__(self):
        return str(self.id)
```

**Comment by klahnakoski** [comment]
@richlysakowski 

>  There was a little confusion on my part between the naming of moz_sql_parser and mo_sql_parsing, and more confusion between "mo" and "moz" and "_" and "-" in package names.

I use dashes for the repository name, and underscore for the module name.  This ensures they do not get mixed up on the off chance the PYTHONPATH is off.

**Comment by bbagley-petsafe** [comment]
I don't believe this issue is fixed.  I have a fresh virtual environment running python 3.11 and the only package installed is ``.  Upon import I received this error

```
ImportError                               Traceback (most recent call last)
Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
----> [1](vscode-notebook-cell:?execution_count=1&line=1) import moz_sql_parser

File [~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:15](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:15)
     [12](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:12) import json
     [13](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:13) from threading import Lock
---> [15](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:15) from moz_sql_parser.sql_parser import SQLParser, scrub_literal, scrub
     [17](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:17) parseLocker = Lock()  # ENSURE ONLY ONE PARSING AT A TIME
     [20](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/__init__.py:20) def parse(sql):

File [~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:12](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:12)
      [1](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:1) # encoding: utf-8
      [2](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:2) #
      [3](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:3) # This Source Code Form is subject to the terms of the Mozilla Public
   (...)
      [7](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:7) # Contact: Kyle Lahnakoski (kyle@lahnakoski.com)
      [8](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:8) #
     [10](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:10) from __future__ import absolute_import, division, unicode_literals
---> [12](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:12) from mo_parsing.engine import Engine
     [13](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:13) from mo_parsing.helpers import delimitedList, restOfLine
     [14](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/moz_sql_parser/sql_parser.py:14) from moz_sql_parser.keywords import *

File [~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:60](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:60)
     [56](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:56) engine.PLAIN_ENGINE = Engine("").use()
     [57](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:57) engine.STANDARD_ENGINE = Engine().use()
---> [60](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:60) from mo_parsing.infix import LEFT_ASSOC, RIGHT_ASSOC, infixNotation
     [61](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:61) from mo_parsing.regex import Regex
     [62](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/__init__.py:62) from mo_parsing.results import ParseResults, engine

File [~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:4](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:4)
      [2](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:2) import re
      [3](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:3) import warnings
----> [4](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:4) from collections import Iterable
      [6](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:6) from mo_dots import listwrap
      [7](https://file+.vscode-resource.vscode-cdn.net/Users/a100099/Documents/data-export-script-jan-2024/~/Documents/data-export-script-jan-2024/.venv/lib/python3.11/site-packages/mo_parsing/infix.py:7) from mo_future import text

ImportError: cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
```
