### ISSUE TITLE
parse method breaks with trim function

### ISSUE THREAD

**Issue by tejkm** [klahnakoski/mo-sql-parsing#19]
The parse method breaks when the SQL has something similar to `trim(both ' ' from ' This is a test')` 

The parser breaks because, the **from** is a keyword. The only way I have worked around is to regex replace this kind of occurrence using the following:
`re.sub("trim\(.*?\)",'trim()',sql, flags=re.DOTALL|re.I)`

```
>>> from moz_sql_parser import parse
>>> sql = "select trim(' ' from ' This is a test') from dual"
>>> parse(sql)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/moz_sql_parser/__init__.py", line 23, in parse
    parse_result = SQLParser.parseString(sql, parseAll=True)
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/mo_parsing/core.py", line 72, in output
    return func(self, *args[1:], **kwargs)
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/mo_parsing/core.py", line 275, in parseString
    return self._parseString(string, parseAll=parseAll)
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/mo_parsing/core.py", line 289, in _parseString
    StringEnd()._parse(string, end)
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/mo_parsing/core.py", line 233, in _parse
    result = self.parseImpl(string, index, doActions)
  File "/Users/tej/virtualenvs/lib/python3.8/site-packages/mo_parsing/tokens.py", line 657, in parseImpl
    raise ParseException(self, start, string)
mo_parsing.exceptions.ParseException: Expecting StringEnd, found "(' ' from " (at char 11, (line:1, col:12)
>>> 
```

**Comment by klahnakoski** [comment]
the solution may not be to your liking:  https://github.com/klahnakoski/mo-sql-parsing/commit/f4f6d4ae410d679212d723d87d1b212864bb59e6
