### ISSUE TITLE
Parse Fails for Tables with One or More Dashes in the Column Name

### ISSUE THREAD

**Issue by LenaJava** [klahnakoski/mo-sql-parsing#50]
>>> from mo_sql_parsing import parse_mysql, parse
>>> q = "select col-cpu-usage from test-information"
>>> parse_mysql(q)
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 144, in _parseString
    StringEnd()._parse(string, end)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 437, in _parse
    result = self.parseImpl(string, start, doActions)
  File "env/lib/python3.8/site-packages/mo_parsing/tokens.py", line 659, in parseImpl
    raise ParseException(self, start, string)
mo_parsing.exceptions.ParseException: Expecting StringEnd, found "-informati" (at char 30), (line:1, col:31)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 146, in _parseString
    raise ParseException(self.element, 0, string, cause=tokens.failures+[pe])
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-informati" (at char 30), (line:1, col:31)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 52, in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
  File "env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 62, in _parse
    parse_result = parser.parseString(sql, parseAll=True)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 79, in output
    return func(*args, **kwargs)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 135, in parseString
    return self._parseString(string, parseAll=parseAll)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 153, in _parseString
    raise cause.best_cause
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-informati" (at char 30), (line:1, col:31)

>>> q = "select 'col-cpu-usage' from test-information"
>>> parse_mysql(q)
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 144, in _parseString
    StringEnd()._parse(string, end)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 437, in _parse
    result = self.parseImpl(string, start, doActions)
  File "env/lib/python3.8/site-packages/mo_parsing/tokens.py", line 659, in parseImpl
    raise ParseException(self, start, string)
mo_parsing.exceptions.ParseException: Expecting StringEnd, found "-informati" (at char 32), (line:1, col:33)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 146, in _parseString
    raise ParseException(self.element, 0, string, cause=tokens.failures+[pe])
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-informati" (at char 32), (line:1, col:33)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 52, in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
  File "env/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 62, in _parse
    parse_result = parser.parseString(sql, parseAll=True)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 79, in output
    return func(*args, **kwargs)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 135, in parseString
    return self._parseString(string, parseAll=parseAll)
  File "env/lib/python3.8/site-packages/mo_parsing/core.py", line 153, in _parseString
    raise cause.best_cause
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-informati" (at char 32), (line:1, col:33)
>>>

**Comment by LenaJava** [comment]
still the parse result for below query is: 
"select average-cpu-usage from test-table-name limit 3"
{'select': {'value': {'literal': 'average-cpu-usage'}}, 'from': 'test-table-name', 'limit': 3}

maybe it should something like blow?
{'select': {'value':  'average-cpu-usage'}, 'from': 'test-table-name', 'limit': 3}

**Comment by klahnakoski** [comment]
This is an interesting "bug", and it is one that I often encounter.  The problem with dashes in names is that they are difficult to distinguish from subtraction.

**Comment by LenaJava** [comment]
yes, not only the dashes, but also the dot in query columns have some problem to parse.
>>> q = "select col.aa.val from test-table-name"
>>> parse_mysql(q)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 150, in _parseString
    StringEnd()._parse(string, end)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 457, in _parse
    result = self.parse_impl(string, start, do_actions)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/tokens.py", line 734, in parse_impl
    raise ParseException(self, start, string)
mo_parsing.exceptions.ParseException: Expecting StringEnd, found "-table-nam" (at char 27), (line:1, col:28)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 152, in _parseString
    raise ParseException(
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-table-nam" (at char 27), (line:1, col:28)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 52, in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
  File "/usr/local/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 62, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 79, in output
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 141, in parse_string
    return self._parseString(string, parse_all=parse_all)
  File "/usr/local/lib/python3.8/site-packages/mo_parsing/core.py", line 161, in _parseString
    raise cause.best_cause
mo_parsing.exceptions.ParseException: Expecting {union} | {intersect} | {except} | {minus} | {order} | {limit} | {offset} | {StringEnd}, found "-table-nam" (at char 27), (line:1, col:28)
>>>

**Comment by klahnakoski** [comment]
`"select col.aa.val from test-table-name"` is parsing dots fine.  The dashes in the table name are the problem; add double quotes around table name. 

    select col.aa.val from "test-table-name"

**Comment by klahnakoski** [comment]
added better error description for this problem:

https://github.com/klahnakoski/mo-sql-parsing/commit/99d47f3489b2ad95cc9f5b6fa07b0945fc59ddd9#diff-6e5030d96839d3fe377cf209b6cab5b0d50ae900b458248d8c24b61774117170R58
