### ISSUE TITLE
Parsing a MySQL `Create table` query raises a ParseException

### ISSUE THREAD

**Issue by onlyacat** [klahnakoski/mo-sql-parsing#74]
This is the query
```sql
CREATE TABLE if not exists `1`  (
    `id` bigint(20) unsigned NOT NULL,
    `a` float NOT NULL DEFAULT '0',
    `b` char(32) NOT NULL DEFAULT '',
    `updated_at` datetime NOT NULL DEFAULT '2021-12-12 00:00:00',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

And both of the `parse` function and the `parse_mysql` function raise a ParseException:

```
mo_sql_parsing.parse_mysql(sql)
Traceback (most recent call last):
  .......
  File "/home/ubuntu/py37/venv/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 53, in parse_mysql
    return _parse(mysql_parser, sql, null, calls)
  File "/home/ubuntu/py37/venv/lib/python3.8/site-packages/mo_sql_parsing/__init__.py", line 78, in _parse
    parse_result = parser.parse_string(sql, parse_all=True)
  File "/home/ubuntu/py37/venv/lib/python3.8/site-packages/mo_parsing/core.py", line 78, in output
    return func(*args, **kwargs)
  File "/home/ubuntu/py37/venv/lib/python3.8/site-packages/mo_parsing/core.py", line 140, in parse
    return self._parseString(string, parse_all=parse_all)
  File "/home/ubuntu/py37/venv/lib/python3.8/site-packages/mo_parsing/core.py", line 162, in _parseString
    raise cause.best_cause from None
mo_parsing.exceptions.ParseException: Expecting ), found "(20) unsig" (at char 44), (line:1, col:45)
```

I would appreciate it if anyone could help me

**Comment by onlyacat** [comment]
The function can work when omitting the identifier `unsigned `, `DEFAULT CHARSET=utf8` and the len of cols `(20)`, `(32)`.

**Comment by klahnakoski** [comment]
fixed here: https://github.com/klahnakoski/mo-sql-parsing/commit/a212ce5c8007547bba501dac45f5c993e25aa284#diff-5592e672cef095f585fc0083c44cdfb8aafdfc11904a484dfa2b0794b0079f35R769

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/8.25.22004/

**Comment by onlyacat** [comment]
@klahnakoski Thanks！
